---
mender_server: https://hosted.mender.io
subscribed_branch: production
playbook_url: edge-playbook
playbook_version: 1.5.0

monitoring_influxdb_server: eu-central-1-1.aws.cloud2.influxdata.com
monitoring_influxdb_bucket: edge-bucket
monitoring_influxdb_org: iot-demo-fleet

os_image:
  - device_type: pi2-armhf
    image_name: 2025-10-10-1056-pi2-gitops-bookworm-armhf
  - device_type: pi3-v3-arm64
    image_name: 2025-10-09-1716-pi3-gitops-trixie-arm64
  - device_type: pi4-v3-arm64
    image_name: 2025-10-10-2137-pi4-gitops-v2-bookworm-arm64
  - device_type: pi5-v3-arm64
    image_name: 2025-10-10-0948-pi5-gitops-bookworm-arm64
  - device_type: var-som-mx8m-nano-arm64-v2
    image_name: 2025-10-10-1001-var-som-mx8m-nano-gitops-bookworm-arm64
  - device_type: iot-gate-imx8-arm64-v2
    image_name: 2025-10-10-1007-iot-gate-imx8-gitops-bookworm-arm64
  - device_type: iot-din-imx8plus-arm64-v2
    image_name: 2025-10-09-1650-iot-din-imx8plus-gitops-trixie-arm64

