---
- name: Apply OS and configuration to fleet.
  hosts: all
  gather_facts: no

  roles:
    - role: gather_fleet_facts
    - role: install_os
      when: subscribed_branch == applied_branch
    - role: apply_configuration
      when: configuration.template is defined
