---
- name: Apply OS and configuration to fleet.
  hosts: all
  gather_facts: no

  vars:
    playbook_mode: "{{ lookup('env', 'PLAYBOOK_MODE') | default('dry-run') }}"

  roles:
    - role: gather_fleet_facts
    - role: install_os
      when: subscribed_branch == applied_branch
    - role: apply_configuration
      when: subscribed_branch == applied_branch and configuration.template is defined
