---

- name: Render desired configuration.
  ansible.builtin.set_fact:
    desired_configuration: "{{ lookup('template', configuration.template) }}"

- name: Set fact for configuration update.
  ansible.builtin.set_fact:
    needs_configuration_update: "{{ reported_configuration != desired_configuration or needs_os_update }}"

- name: Announce configuration upgrade.
  ansible.builtin.debug:
    msg: "Applying template {{ configuration.template }}."
  when: needs_configuration_update

- name: Show detailed configuration change.
  ansible.builtin.debug:
    msg: "Configuration: {{ reported_configuration }} --> {{ desired_configuration }}."
  when: needs_configuration_update and playbook_mode == "dry-run-debug"

- name: Set device configuration.
  ansible.builtin.uri:
    url: "{{ mender_server }}/api/management/v1/deviceconfig/configurations/device/{{ inventory_hostname }}"
    method: PUT
    headers:
      Accept: application/json
      Authorization: Bearer {{ mender_access_token }}
    body_format: json
    body: "{{ desired_configuration }}"
    status_code: 204
  delegate_to: 127.0.0.1
  changed_when: true
  when: needs_configuration_update and playbook_mode == "run"

- name: Deploy device configuration.
  ansible.builtin.uri:
    url: "{{ mender_server }}/api/management/v1/deviceconfig/configurations/device/{{ inventory_hostname }}/deploy"
    method: POST
    headers:
      Accept: application/json
      Authorization: Bearer {{ mender_access_token }}
    body_format: json
    body: "{}"
  delegate_to: 127.0.0.1
  changed_when: true
  when: needs_configuration_update and playbook_mode == "run"
