---

- name: Render desired configuration.
  ansible.builtin.set_fact:
    desired_configuration: "{{ lookup('template', configuration.template)  }}"

- name: Announce configuration upgrade.
  ansible.builtin.debug:
    msg: "Applying template {{ configuration.template }}."
  when: reported_configuration != desired_configuration

- name: Set device configuration.
  ansible.builtin.uri:
    url: "{{ mender_server }}/api/management/v1/deviceconfig/configurations/device/{{ inventory_hostname }}"
    method: PUT
    headers:
      Accept: application/json
      Authorization: Bearer {{ mender_token.cookies.JWT }}
    body_format: json
    body: "{{ desired_configuration }}"
    status_code: 204
  delegate_to: 127.0.0.1
  changed_when: True
  when: reported_configuration != desired_configuration

- name: Deploy device configuration.
  ansible.builtin.uri:
    url: "{{ mender_server }}/api/management/v1/deviceconfig/configurations/device/{{ inventory_hostname }}/deploy"
    method: POST
    headers:
      Accept: application/json
      Authorization: Bearer {{ mender_token.cookies.JWT }}
    body_format: json
    body: "{}"
  delegate_to: 127.0.0.1
  changed_when: True
  when: reported_configuration != desired_configuration
