---

- name: Set facts for OS update.
  ansible.builtin.set_fact:
    os_image_name: "{{ os_image | community.general.json_query(os_image_query) | first  }}"
  vars:
    os_image_query: "[?device_type==`{{ device_type }}`].image_name"

- name: Announce OS update.
  ansible.builtin.debug:
    msg: "Updating to {{ os_image_name }}, device type: {{ device_type }}"

- name: Apply OS update.
  ansible.builtin.uri:
    url: "{{ mender_server }}/api/management/v1/deployments/deployments"
    method: POST
    headers:
      Accept: application/json
      Authorization: Bearer {{ mender_token.cookies.JWT }}
    body_format: json
    body: "{{ lookup('template','os-update.json') }}"
    status_code: 201
  delegate_to: 127.0.0.1
  changed_when: True
