---
subscribed_branch: develop

playbook_version: 1.1.123

kiosk_enabled: true
kiosk_kiosk_url: https://docs.get-edi.io

monitoring_enabled: true
monitoring_influxdb_http_token: "{{ lookup('env', 'INFLUXDB_HTTP_TOKEN') }}"
