name: update fleet
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out the fleet management playbook
        uses: actions/checkout@v3
      - name: Install jmespath into venv of ansible-core
        run: pipx inject ansible-core jmespath
      - name: Run the fleet management playbook
        uses: dawidd6/action-ansible-playbook@v4
        with:
          playbook: manage-fleet.yml
          options: --inventory inventory.yml
        env:
          MENDER_ACCESS_TOKEN: ${{ secrets.MENDER_ACCESS_TOKEN }}
          RUNNER_ACCESS_TOKEN: ${{ secrets.RUNNER_ACCESS_TOKEN }}
          INFLUXDB_HTTP_TOKEN: ${{ secrets.INFLUXDB_HTTP_TOKEN }}
          PLAYBOOK_MODE: run
